# This workflow will build the website with pelican using a hierarchy pluging
# and publish (deploy) it to a webserver

name: Publish website

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'website'
      # will checkout the website repository as the default action

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pelican markdown pybtex

    - name: Checkout VIANNA-theme
      uses: actions/checkout@v2
      with:
        repository: 'vianna-research/VIANNA-theme'
        path: 'VIANNA-theme'
     
    - name: Checkout hierarchy plugin (from Samuels fork of pelican-plugins)
      uses: actions/checkout@v2
      with:
        repository: 'samueljohn/pelican-plugins'
        path: 'pelican-plugins'
        
    - name: Checkout pelican-cite plugin (for bibliography)
      uses: actions/checkout@v2
      with:
        repository: 'vianna-research/pelican-cite'
        path: 'pelican-cite-plugin/pelican-cite'
        
    - name: Build website
      id: build
      run: |
        ls
        pelican -s website/pelicanconf.py -v -D 
        ls -la html/
    - name: Sync files to web server
      id: deploy
      uses: Burnett01/rsync-deployments@4.1
      # Generate key pair for deployment on a server like so:
      # SSH in to the website server
      # ssh-keygen -f ~/.ssh/deploy_key_rsa -q -P "" 
      # cat ~/.ssh/deploy_key_rsa.pub
      # and copy it
      # Add pub key to ~/.ssh/authorized_hosts
      # Add private deploy_key_rsa to Github as a secret on the repository for the website
      with:
        switches: -avzr --delete
        path: html/
        remote_path: /var/www/virtual/vianna/html/
        remote_host: vianna.uber.space
        remote_user: vianna
        remote_key: ${{ secrets.DEPLOY_KEY }}
